### ISSUE TITLE
So close... Enable CORS didn't work...

### ISSUE THREAD

**Issue by markerx** [JustServerless/learnserverless-book#3]
I used the Enable CORS function in the API Gateway:

![](http://f.cl.ly/items/0f1i28273I3C3D2k1z30/Image%202016-03-24%20at%206.22.14%20PM.png)

But I am still getting the CORS related error:

![](http://f.cl.ly/items/2g0h2W1i1a3I3j0s0M0w/Image%202016-03-24%20at%206.23.14%20PM.png)

What did I do wrong?

Thanks!

**Comment by pmuens** [comment]
Hey @markerx 
we've updated the book yesterday (Version 2.0.1) which covers this. You need to enable CORS for every endpoint

`/notes`and `/notes/id` are missing. Just enable CORS for them as well and deploy the API. Then it should be fine.

Let me know if it fixes your problem!

**Comment by markerx** [comment]
FYI - the CORS plugin was updated today.

https://github.com/joostfarla/serverless-cors-plugin

With a little stumbling around, I was able to add it to my project and getting everything working,

**Comment by pmuens** [comment]
Great! Thanks for the pointer! Yes, we're updating it the upcoming week!
