### ISSUE TITLE
Where can I find the book source code?

### ISSUE THREAD

**Issue by dinnouti** [JustServerless/learnserverless-book#4]
Hi Philipp, I bought the book Just Serverless, and I am looking for the source code repository, mainly to copy and paste the dyanamodb s-resources-cf.json code. Where can I find the source code?

thanks!

**Comment by pmuens** [comment]
Hey @dinnouti thank you for your question!
You can find the full source code here: https://github.com/JustServerless/notes

Let me know if you have any questions!
