### ISSUE TITLE
Where is GET url referenced in doc on page 28 after deploying 'greeter'?

### ISSUE THREAD

**Issue by bartonhammond** [JustServerless/learnserverless-book#5]
On page 28 the following is written but there is no URL

> Wait until Serverless has finished and copy the generated GET URL from the terminal output. Open up a browser with this link and see how your first Lambda function is executed in the AWS cloud.

Here is my output

```

Serverless: Select the assets you wish to deploy:
    greeter
      function - greeter
      endpoint - greeter - GET
    - - - - -
  > Deploy
    Cancel

Serverless: Deploying the specified functions in "development" to the following regions: eu-central-1  
Serverless: ------------------------  
Serverless: Successfully deployed the following functions in "development" to the following regions:   
Serverless: eu-central-1 ------------------------  
Serverless:   greeter (helloworld-greeter): arn:aws:lambda:eu-central-1:843112854210:function:helloworld-greeter:development 
```

**Comment by pmuens** [comment]
Have you deployed the endpoint as well (you need to check both)?

**Comment by bartonhammond** [comment]
Ah - that wasn't clear to me.

The book says

> Deployment
> Let's deploy our API Gateway and Lambda function. Open the deployment dashboard with the
>   serverless dash deploy
> command and select the functions gateway and the function from the menu.

And the prompt is

```
Serverless: Select the assets you wish to deploy:
    greeter
      function - greeter
      endpoint - greeter - GET
    - - - - -
  > Deploy
    Cancel
```

Maybe the book should say `deploy the function and endpoint`.

**Comment by pmuens** [comment]
Alright. Thanks for the feedback!
