### ISSUE TITLE
API Gateway not active on pg 51

### ISSUE THREAD

**Issue by bartonhammond** [JustServerless/learnserverless-book#7]
On pg 51, I read:

> Go to your AWS console after the deployment has finished and open the API Gateway service.

When I go to AWS console I see:
<img width="1352" alt="screen shot 2016-06-21 at 11 06 55 am" src="https://cloud.githubusercontent.com/assets/1282364/16237080/5d76de10-37a0-11e6-8183-54e98ff05835.png">

<img width="846" alt="screen shot 2016-06-21 at 11 03 12 am" src="https://cloud.githubusercontent.com/assets/1282364/16236942/ccd162e0-379f-11e6-95b0-02aae0f8d9e8.png">

And when I select `API Gateway` I see:

<img width="1346" alt="screen shot 2016-06-21 at 11 01 01 am" src="https://cloud.githubusercontent.com/assets/1282364/16236965/ea6a32c8-379f-11e6-82ba-406028194b38.png">

Here is output from previous deploy on pg 50:

```
Serverless: Select the assets you wish to deploy:
    create
      function - create
      endpoint - notes - POST
    - - - - -
  > Deploy
    Cancel

Serverless: Deploying the specified functions in "development" to the following regions: eu-central-1  
Serverless: ------------------------  
Serverless: Successfully deployed the following functions in "development" to the following regions:   
Serverless: eu-central-1 ------------------------  
Serverless:   create (notes-create): arn:aws:lambda:eu-central-1:843112854210:function:notes-create:development  

Serverless: Deploying endpoints in "development" to the following regions: eu-central-1  
Serverless: Successfully deployed endpoints in "development" to the following regions:  
Serverless: eu-central-1 ------------------------  
Serverless:   POST - notes - https://p8uqe7akg4.execute-api.eu-central-1.amazonaws.com/development/notes  
~/projects/Serverless/notes$ 
```

Is there a step missing to setup `API Gateway`?

**Comment by bartonhammond** [comment]
Here is the current state of my following along w/ the book up to page 51, "Testing".

[https://github.com/bartonhammond/serverless-notes](https://github.com/bartonhammond/serverless-notes)

**Comment by pmuens** [comment]
You've deployed to `eu-central-1` (Frankfurt) but looking at `us-east-1` (N. Virginia) in your AWS console.

**Comment by bartonhammond** [comment]
Ah!  The book makes no mention of that the region deployed must match the dropdown of the console.  A note to that effect would be great!  Thanks for quick responses!

**Comment by pmuens** [comment]
Yep. That's right. Thank you for mentioning that!
